
import { GoogleGenAI } from "@google/genai";
import { MODEL_NAME } from "../constants";

export const generateMixedPoster = async (
  images: string[], 
  prompt: string
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  
  // Convert images to Gemini parts
  const imageParts = await Promise.all(
    images.map(async (url) => {
      // If it's a data URL, extract the base64 and mime
      if (url.startsWith('data:')) {
        const matches = url.match(/^data:([^;]+);base64,(.+)$/);
        if (matches) {
          return {
            inlineData: {
              mimeType: matches[1],
              data: matches[2]
            }
          };
        }
      }
      
      // If it's a regular URL, we need to fetch and convert (proxy-like or simple fetch if allowed)
      const response = await fetch(url);
      const blob = await response.blob();
      const base64 = await new Promise<string>((resolve) => {
        const reader = new FileReader();
        reader.onloadend = () => resolve((reader.result as string).split(',')[1]);
        reader.readAsDataURL(blob);
      });
      
      return {
        inlineData: {
          mimeType: blob.type,
          data: base64
        }
      };
    })
  );

  const fullPrompt = `Create a professional advertising poster for WhatsApp status. 
  You must blend elements from the provided images:
  1. The golden vape device (luxurious, high-tech).
  2. The 'El Patrón' man with his hat and sunglasses and the golden branding style.
  3. The epic cosmic astronaut theme.
  
  User specific instructions: ${prompt}
  
  The final output should be a single, stunning composite image featuring an astronaut in a dark, glowing space environment holding the golden vape pod. 
  Integrate the "El Patrón" logo/branding naturally into the cosmic scene, perhaps as a nebula or a holographic projection. 
  The aesthetic must be premium, dark, with gold and blue neon accents. Cinematic lighting.`;

  const response = await ai.models.generateContent({
    model: MODEL_NAME,
    contents: {
      parts: [
        ...imageParts,
        { text: fullPrompt }
      ]
    },
    config: {
      imageConfig: {
        aspectRatio: "9:16" // Ideal for WhatsApp Status
      }
    }
  });

  let imageUrl = '';
  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      imageUrl = `data:image/png;base64,${part.inlineData.data}`;
      break;
    }
  }

  if (!imageUrl) {
    throw new Error("No image was generated by the model.");
  }

  return imageUrl;
};
